-- This module is the root of the PoincareConjectureCanonicalLaneLean Lean proof package.
import PoincareConjectureCanonicalLaneLean.Basic
import PoincareConjectureCanonicalLaneLean.SourcePackage
import PoincareConjectureCanonicalLaneLean.SourceDependencies
import PoincareConjectureCanonicalLaneLean.Formalization
import PoincareConjectureCanonicalLaneLean.ReviewerBridge
import PoincareConjectureCanonicalLaneLean.TheoremStatement
import PoincareConjectureCanonicalLaneLean.MathlibObjects
import PoincareConjectureCanonicalLaneLean.AdmissibleClass
import PoincareConjectureCanonicalLaneLean.Projection
import PoincareConjectureCanonicalLaneLean.BridgeLemmas
import PoincareConjectureCanonicalLaneLean.GateLemmas
import PoincareConjectureCanonicalLaneLean.FinalTheorem
import PoincareConjectureCanonicalLaneLean.PerelmanRoute
import PoincareConjectureCanonicalLaneLean.MathlibStatement
